---
- name: Clone Emacs Lisp repos
  git:
    repo: "https://github.com/mrkkrp/{{ item }}.git"
    dest: "~/projects/programs/emacs-lisp/{{ item }}"
    version: master
  with_items: "{{ projects_to_clone.emacs_lisp }}"
- name: Clone Common Lisp repos
  git:
    repo: "https://github.com/mrkkrp/{{ item }}.git"
    dest: "~/projects/programs/common-lisp/{{ item }}"
    version: master
  with_items: "{{ projects_to_clone.common_lisp }}"
- name: Clone Haskell repos
  git:
    repo: "https://github.com/mrkkrp/{{ item }}.git"
    dest: "~/projects/programs/haskell/{{ item }}"
    version: master
  with_items: "{{ projects_to_clone.haskell }}"
- name: Clone MMark repos
  git:
    repo: "https://github.com/mmark-md/{{ item }}.git"
    dest: "~/projects/programs/mmark/{{ item }}"
    version: master
- name: Hasky Mode repos
  git:
    repo: "https://github.com/hasky-mode/{{ item }}.git"
    dest: "~/projects/programs/hasky-mode/{{ item }}"
    version: master
  with_items: "{{ projects_to_clone.hasky_mode }}"
- name: Other repos
  git:
    repo: "https://github.com/mrkkrp/{{ item }}.git"
    dest: "~/projects/programs/other/{{ item }}"
    version: master
  with_items: "{{ projects_to_clone.other }}"
- name: Python repos
  git:
    repo: "https://github.com/mrkkrp/{{ item }}.git"
    dest: "~/projects/programs/python/{{ item }}"
    version: master
  with_items: "{{ projects_to_clone.python }}"
