---
- name: Create the Downloads directory
  file:
    path: "~/Downloads"
    state: directory
- name: Download archives of packages to install manually
  get_url:
    url: "https://aur.archlinux.org/cgit/aur.git/snapshot/{{ item }}.tar.gz"
    dest: "/tmp"
  with_items: "{{ manual_packages }}"
- name: Uncompress packages for manual installation
  unarchive:
    src: "/tmp/{{ item }}.tar.gz"
    dest: "/tmp"
  with_items: "{{ manual_packages }}"
- name: Build and install the packages from decompressed files
  command: "makepkg -si --noconfirm"
  args:
    chdir: "/tmp/{{ item }}"
  with_items: "{{ manual_packages }}"
- name: Create alternative yaourt working directory
  file:
    path: "~/{{ yaourt_work_dir }}"
    state: directory
- name: Tell yaourt to use the alternative working directory instead
  lineinfile:
    dest: "/etc/yaourtrc"
    regexp: "^TMPDIR="
    line: "TMPDIR=\"/home/{{ user_name }}/{{ yaourt_work_dir }}\""
    state: present
  become: yes
- name: Install packages with Yaourt
  command: "yaourt -S --noconfirm {{ item }} && touch ~/{{ yaourt_work_dir }}/installed-{{ item }}"
  args:
    creates: "~/{{ yaourt_work_dir }}/installed-{{ item }}"
  with_items: "{{ yaourt_packages }}"
